<template>
  <div>
    <iframe
      src="https://open.spotify.com/follow/1/?uri=spotify:artist:6sFIWsNpZYqfjUpaCgueju&size=detail&theme=light"
      width="300"
      height="56"
      scrolling="no"
      frameborder="0"
      style="border:none; overflow:hidden;"
      allowtransparency="true"
    ></iframe>
    <iframe
      src="https://open.spotify.com/embed/album/1DFixLWuPkv3KT3TnV35m3"
      width="300"
      height="380"
      frameborder="0"
      allowtransparency="true"
      allow="encrypted-media"
    ></iframe>
  </div>
</template>
